name: Build WASM && Fire Deployment Action

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_run:
    workflows: ["Test JS Utils"]
    types: [completed]

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install LLVM and WASI SDK
        shell: bash
        run: |
          make install toolchain="llvm-wasi"
      - name: Make WASM
        shell: bash
        run: |
          for target in $(ls -d src/*_demo);
          do
              make -B $target/main.wasm include-wasi-sdk=1 verbose=1;
          done
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./src
